/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao;

import Construtor.Controlador_telas;

/**
 *
 * @author alunos
 */
public class Tela_administrador extends javax.swing.JPanel {
Controlador_telas controlador_telas;

    /**
     * Creates new form Tela_administrador
     */
    public Tela_administrador(Controlador_telas controlador_telas3) {
        initComponents();
        controlador_telas = controlador_telas3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtoncadastroproduto = new javax.swing.JButton();
        jButtoncadastrousuario = new javax.swing.JButton();
        jButtontellogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtoncadastroproduto.setText("Cadastar produto");
        jButtoncadastroproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoncadastroprodutoMouseClicked(evt);
            }
        });
        jButtoncadastroproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastroprodutoActionPerformed(evt);
            }
        });

        jButtoncadastrousuario.setText("Cadastrar usuário");
        jButtoncadastrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastrousuarioActionPerformed(evt);
            }
        });

        jButtontellogin.setText("Tela de login");
        jButtontellogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontelloginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Você deseja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jButtoncadastroproduto, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jButtoncadastrousuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtontellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jButtoncadastrousuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncadastroproduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtontellogin)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncadastroprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoncadastroprodutoMouseClicked
  
    }//GEN-LAST:event_jButtoncadastroprodutoMouseClicked

    private void jButtoncadastroprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastroprodutoActionPerformed
        controlador_telas.Cadastrar_produto(controlador_telas);
    }//GEN-LAST:event_jButtoncadastroprodutoActionPerformed

    private void jButtoncadastrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastrousuarioActionPerformed
        controlador_telas.Usuario(controlador_telas);
    }//GEN-LAST:event_jButtoncadastrousuarioActionPerformed

    private void jButtontelloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontelloginActionPerformed
        controlador_telas.Login(controlador_telas);
    }//GEN-LAST:event_jButtontelloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncadastroproduto;
    private javax.swing.JButton jButtoncadastrousuario;
    private javax.swing.JButton jButtontellogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
